CREATE DATABASE COINS_MANAGE
GO
USE COINS_MANAGE
GO

--ĐÂY LÀ BẢNG TÀI KHOẢN VÀ MẬT KHẨU CỦA CLIENT
CREATE TABLE ACCOUNT
(
	ID       INT IDENTITY PRIMARY KEY,
	USERNAME VARCHAR(30),
	PASS     VARCHAR(30)
)
GO

--ĐÂY LÀ BẢNG LƯU GIỮ LIỆU TỪ DATA
CREATE TABLE COINS_DATA
(
	ID            INT IDENTITY PRIMARY KEY,
	CURRENCY      VARCHAR(10),
	BUY_CASH      DOUBLE PRECISION,
	BUY_TRANSFER  DOUBLE PRECISION,
	SELL          DOUBLE PRECISION,
	DATE_TIME	  DATETIME
)
GO
ALTER TABLE COINS_DATA
ALTER COLUMN DATE_TIME DATETIME

-------PROCEDURE---------------
CREATE PROCEDURE INSERT_COINSDATA @CURRENCY VARCHAR(10),@BUY_CASH DOUBLE PRECISION,@BUY_TRANSFER DOUBLE PRECISION,@SELL DOUBLE PRECISION
AS
	INSERT INTO COINS_DATA (CURRENCY,BUY_CASH,BUY_TRANSFER,SELL,DATE_TIME)
	VALUES 
		(@CURRENCY,@BUY_CASH,@BUY_TRANSFER,@SELL,GETDATE())

SELECT * FROM COINS_DATA

SELECT COUNT(*) FROM COINS_DATA WHERE DAY(DATE_TIME) = 17 AND MONTH(DATE_TIME) = 11 AND YEAR(DATE_TIME) = 2021

SELECT COUNT(*) FROM COINS_DATA WHERE CURRENCY = 'AUD'
